MONGODB_DB_NAME = "STAFF"
MONGODB_URL = "mongodb://localhost:27017/"
MONGODB_HR_COLLECTIONS = "HR"
MONGODB_EMP_COLLECTIONS = "EMPLOYEE"
API_V1_STR = "/api/v1"
MAX_CONNECTIONS_COUNT = 10
MIN_CONNECTIONS_COUNT = 1